### ISSUE TITLE
Feature Request - Add variable for disable_password_authentication to allow for this to be configured

### ISSUE THREAD

**Issue by kalenarndt** [intel/terraform-intel-azure-linux-vm#2]
**Is your feature request related to a problem? Please describe.**

No problems!

**Describe the solution you'd like**
Add a variable for the parameter `disable_password_authentication` instead of a hard coded bool

https://github.com/intel/terraform-intel-azure-linux-vm/blob/1b9dcabc963cac1acb94990b4e1c44f64769a87e/main.tf#L46

**Describe alternatives you've considered**
N/A

**Explain any additional use-cases**
N/A

**Additional context**

Microsoft recommends this being set to `true` which is the default value. Any changes on this object forces a new resource to be created. If this isn't an option for people then when they go to change it, it can cause the object to be destroyed

**Comment by lucasmelogithub** [comment]
Thanks for the feedback, variable has been implemented. 

https://github.com/intel/terraform-intel-azure-linux-vm/blob/0022ccd1886a8fe4c9dcbb2d96dd9d9781a56bdf/main.tf#L54-L55
