### ISSUE TITLE
Missing descriptions from outputs in outputs.tf in the module

### ISSUE THREAD

**Issue by kalenarndt** [intel/terraform-intel-azure-linux-vm#3]
**Is your feature request related to a problem? Please describe.**

No problems

**Describe the solution you'd like**

Add descriptions to all of the outputs in the `outputs.tf` file. This will allow users to understand the configured outputs as well as document them via `terraform-docs`

**Describe alternatives you've considered**

N/A

**Explain any additional use-cases**

N/A

**Additional context**

https://github.com/intel/terraform-intel-azure-linux-vm/blob/1b9dcabc963cac1acb94990b4e1c44f64769a87e/outputs.tf#L1-L30

**Comment by lucasmelogithub** [comment]
Thanks for the feedback, fixed, closing. 

https://github.com/intel/terraform-intel-azure-linux-vm/blob/main/outputs.tf#L1
