### ISSUE TITLE
Feature Request: Serial Console and Boot Diagnostics

### ISSUE THREAD

**Issue by kvietmeier** [intel/terraform-intel-azure-linux-vm#6]
### Overview
There are situations where you might need access to the serial console and/or view the boot logs of a Linux VM but this is not enabled by default on Azure. 

Requirement:
You have to enable boot diagnostics which requires a storage account to exist. It is common to maintain a storage account per region for this purpose but it can be a on a per vm basis upon creation to avoid leaving bits behind on a destroy.

Required Terraform code - 
~~~terraform
# For serial console and monitoring
  boot_diagnostics {
    storage_account_uri = azurerm_storage_account.diagstorageaccount.primary_blob_endpoint
  }
~~~

### Acceptance Criteria
Core functionality of an IaaS VM for network or kernel troubleshooting.

**Comment by lucasmelogithub** [comment]
Completed as part of PR #5
